### ISSUE TITLE
Windows 10 Image with Auto Logon

### ISSUE THREAD

**Issue by spoer78** [cloudbase/windows-imaging-tools#353]
Hi there,

we are using the imaging tools successfully for Window Server 2016, 2019 and Windows 10 Enterprise with password injection and retrieval via Horizon.

Now we want to introduce Leostream as VDI solution and we need to create Windows 10 Enterprise images with no password and auto-login at first boot. Then the Leostream agent takes over and does its thing.

But till now we weren't successful. The first time the image is booting in Openstack, you are required to login and change the password for the "Admin" user.

Is there a way to create an image that has autologin enabled?

bye
SP

**Comment by ader1990** [comment]
Hello,

You need to create your custom Unattend.xml which you have to use to sysprep the machine manually after installing Cloudbase-Init. That Unattend.xml need to be created in order to set the auto logon. Also, you need to configure Cloudbase-Init not to execute the UserCreate and SetUserPassword plugins.

You can use the RunAfterCloudbaseInitInstall.ps1 hook to configure the Cloudbase-Init config file and the used Unattend.xml for sysprep.

Thank you,
Adrian Vladu
